### ISSUE TITLE
[Feature request] Add new device

### ISSUE THREAD

**Issue by M9k** [f9n/prtg-cli#1]
Hi,
First of all great job, I really like this project.

Are you planning to also bring the functionality to add devices?
Would it be easy to implement the addition of some basic sensors, such as PING?

Thanks a lot.

**Comment by f9n** [comment]
Hi,
Prtg Api does not support adding new devices.

>  [Adding Objects](https://www.paessler.com/manuals/prtg/object_manipulation)
    Adding completely new objects from scratch is not supported via the API due to the complexity of object creation and its parameters. To add new objects to PRTG, create a "master" object that will be cloned into new objects.

Therefore, we created several device types, then cloned them for new devices. Soon I will add a new subcommand(`manager`). In PRTG we will be able to create the device list defined in the Yaml format file.

Example:
```
TEMPLATES (prtg group)
     KUBERNETES_32-CPU_64_MEMORY
     RABBITMQ_PROD_TYPE_1
```

**Comment by M9k** [comment]
Okay,
Thanks a lot for the explanation.
